export type Stats = {
  armor: number,
  armorperlevel: number,
  attackdamage: number,
  attackdamageperlevel: number,
  attackrange: number,
  attackspeed: number,
  attackspeedperlevel: number,
  crit: number,
  critperlevel: number,
  hp: number,
  hpperlevel: number,
  hpregen: number,
  hpregenperlevel: number,
  movespeed: number,
  mp: number,
  mpperlevel: number,
  mpregen: number,
  mpregenperlevel: number,
  spellblock: number,
  spellblockperlevel: number
}
